[project]
name = "feishu-outcsv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.3.3",
    "polars>=1.35.2",
    "requests>=2.32.5",
]
